# Change these first
owner: XzFrosT # Your GitHub username
repo: uptimer # Your GitHub repository name

# Add your sites here
sites:
  - name: Brain Bot Website
    url: https://brain-bot.netlify.app
    icon: https://i.imgur.com/jIqqUie.png

status-website:
  baseUrl: /uptimer
  theme: night
  logoUrl: https://harmonymusic.tk/assets/img/logo.png
  name: XzFrosT
  introTitle: "XzFrosT StatusPage"
  introMessage: StatusPage for all my project
  navbar:
    - title: Home
      href: /uptimer
  i18n:
    footer: © 2020-2021 XzFrosT

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
